/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class OpusEncoder {
  constructor(sampleRate: number, channels: number)
  encode(data: Buffer): Buffer
  decode(data: Buffer): Buffer
  setBitrate(bitrate: number): void
  getBitrate(): number
  applyEncoderCtl(request: number, value: number): void
  applyDecoderCtl(request: number, value: number): void
  destroy(): void
}
